### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by SOVLOOKUP** [kaindev8/starMQ#5]
错误如下：
```
Warning: require(D:\wwwroot\127.0.0.1\starMQ-master\vendor\composer/../symfony/deprecation-contracts/function.php): Failed to open stream: No such file or directory in D:\wwwroot\127.0.0.1\starMQ-master\vendor\composer\autoload_real.php on line 55

Fatal error: Uncaught Error: Failed opening required 'D:\wwwroot\127.0.0.1\starMQ-master\vendor\composer/../symfony/deprecation-contracts/function.php' (include_path='.;C:\php\pear') in D:\wwwroot\127.0.0.1\starMQ-master\vendor\composer\autoload_real.php:55 Stack trace: #0 D:\wwwroot\127.0.0.1\starMQ-master\vendor\composer\autoload_real.php(38): composerRequire93e86bf72fe4d4e5018a59d3a5021a31('6e3fae29631ef28...', 'D:\\wwwroot\\127....') #1 D:\wwwroot\127.0.0.1\starMQ-master\vendor\autoload.php(25): ComposerAutoloaderInit93e86bf72fe4d4e5018a59d3a5021a31::getLoader() #2 D:\wwwroot\127.0.0.1\starMQ-master\public\index.php(22): require('D:\\wwwroot\\127....') #3 {main} thrown in D:\wwwroot\127.0.0.1\starMQ-master\vendor\composer\autoload_real.php on line 55
```

**Comment by hhbusui** [comment]
怎么解决的呀

**Comment by SOVLOOKUP** [comment]
自己安装一下依赖
